### PR TITLE
allow text-2.0

### PR DESCRIPTION
**Pull request by amigalemming**

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
I haven't touched this repo in a while, so CI is not set up properly.

Does `text < 2.1` compile on your machine? If so, I'd be happy to make a Hackage revision.

**Comment by amigalemming** [comment]
On Mon, 23 Jan 2023, Heinrich Apfelmus wrote:

> Does text < 2.1 compile on your machine? If so, I'd be happy to make a 
> Hackage revision.

I can build hyper-0.2.1.1 with text-2.0.1.

**Comment by HeinrichApfelmus** [comment]
> I can build hyper-0.2.1.1 with text-2.0.1.

👍 I have published a revision.

**Comment by amigalemming** [comment]
On Mon, 23 Jan 2023, Heinrich Apfelmus wrote:

>       I can build hyper-0.2.1.1 with text-2.0.1.
> 
> 👍 I have published a revision.

You may also relax to: base <4.19.

I have checked that I can build it with GHC-9.2, GHC-9.4, GHC-9.6.

**Comment by HeinrichApfelmus** [comment]
Did. Thanks!

**Comment by HeinrichApfelmus** [comment]
I have cleaned up the household a little bit — I have updated dependencies, added a Github Action that checks various compiler versions, and made new revisions or releases on Hackage as necessary.

This pull request is now superseded. Thanks for the contribution!

**Pull request closed without merging**
