### PR TITLE
Two fixes for nix

### PR DESCRIPTION
**Pull request by rvl**
I have a patch almost ready to add Hyper Haskell to the Nix packages collection. But before I submit that to nixpkgs:

1. There is a small change required to get the csound vdac to work.
2. I have added a freedesktop.org launcher file which is good for Linux.
3. After merging this, is it possible to make a new git tag release?

Cheers!

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
Sorry for the long delay. Thanks!

Does the git tag need a version number, or is a "temporary" tag ok?

**Comment by rvl** [comment]
Hello @HeinrichApfelmus, no problem, thanks for merging!

The git tag doesn't need to be a version number or match cabal, etc. It could just be called `v0.1.0.1-nix`. The Nix project prefer tags made by the upstream author rather than bare git revision IDs.

**Comment by HeinrichApfelmus** [comment]
Ok, so I made a new tag, [v0.1.0.2][1], which mainly bumps the dependencies for the Haskell parts, but also contains your changes.

  [1]: https://github.com/HeinrichApfelmus/hyper-haskell/releases/tag/v0.1.0.2

**Comment by rvl** [comment]
Excellent, thanks! I'm hoping it will now be as easy to install this on Nix as it is on MacOS X.

**Comment by HeinrichApfelmus** [comment]
My pleasure! It may also be useful to add a few remarks to the README file on how to install it with Nix.

**Pull request merged**
